import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import localFont from 'next/font/local';

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: './fonts/trebuc.ttf' });

export const metadata: Metadata = {
  title: 'MD Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
